---
label: Theme configuration
hide_body: true
fields:
- type: text
  name: Centre_Hospitalier_Belvedere
  label: Centre Hospitalier du Belvédère
  description: 'Réalisation du site du centre hospitalier du Belvédère. '
- type: textarea
  name: site_description
  label: Site description
- type: textarea
  name: hero_title
  label: Hero title
  config:
    wysiwyg: true
    schema:
      format: html
- type: textarea
  name: hero_subtitle
  label: Hero subtitle
  config:
    wysiwyg: true
    schema:
      format: html
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- type: boolean
  name: dark_mode
  label: Dark mode
pages:
- data/theme.json
